name: quickpin
version: 0.1.0
dependencies:
    angular: any
    bootjack: any
    browser: any
    collection: any
    dialog: any
    dnd: any
    intl: any
    route_hierarchical: any
    web_components: any
transformers:
- angular
